import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import AdminLayout from '../../components/AdminLayout';
export default function MultiUnitPage() {
    const products = [
        { name: 'Indomie Goreng', satuan: { pcs: 3500, pack: 32000, dus: 150000 } },
        { name: 'Air Mineral 600ml', satuan: { pcs: 5000, dus: 48000 } },
        { name: 'Minyak Goreng 1L', satuan: { pcs: 18000, karton: 200000 } },
    ];
    return _jsx(AdminLayout, { children: _jsxs("div", { className: "space-y-4 max-w-5xl mx-auto", children: [_jsx("div", { className: "page-header", children: _jsxs("div", { children: [_jsx("h1", { children: "\uD83D\uDCCF Multi Satuan" }), _jsx("p", { className: "text-gray-400 text-sm", children: "Atur harga per satuan berbeda untuk setiap produk" })] }) }), _jsx("div", { className: "table-wrap", children: _jsxs("table", { children: [_jsx("thead", { children: _jsxs("tr", { children: [_jsx("th", { children: "Produk" }), _jsx("th", { children: "Satuan & Harga" }), _jsx("th", { children: "Aksi" })] }) }), _jsx("tbody", { children: products.map((p, i) => (_jsxs("tr", { children: [_jsx("td", { className: "font-medium", children: p.name }), _jsx("td", { children: _jsx("div", { className: "flex flex-wrap gap-2", children: Object.entries(p.satuan).map(([unit, price]) => (_jsxs("span", { className: "badge badge-green", children: [unit, ": Rp ", price.toLocaleString()] }, unit))) }) }), _jsx("td", { children: _jsx("button", { className: "btn btn-sm btn-secondary", children: "Atur" }) })] }, i))) })] }) }), _jsxs("div", { className: "card", children: [_jsx("h3", { className: "font-bold mb-2", children: "\u2795 Tambah Multi Satuan" }), _jsxs("div", { className: "grid md:grid-cols-2 gap-3", children: [_jsxs("div", { children: [_jsx("label", { className: "text-sm font-medium block mb-1", children: "Produk" }), _jsx("select", { className: "input-field", children: _jsx("option", { children: "Indomie Goreng" }) })] }), _jsxs("div", { children: [_jsx("label", { className: "text-sm font-medium block mb-1", children: "Satuan" }), _jsx("input", { className: "input-field", placeholder: "Contoh: karton, lusin, botol" })] }), _jsxs("div", { children: [_jsx("label", { className: "text-sm font-medium block mb-1", children: "Isi per Satuan" }), _jsx("input", { className: "input-field", type: "number", placeholder: "Contoh: 12 (buah per karton)" })] }), _jsxs("div", { children: [_jsx("label", { className: "text-sm font-medium block mb-1", children: "Harga Satuan" }), _jsx("input", { className: "input-field", type: "number", placeholder: "Contoh: 40000" })] })] }), _jsx("button", { className: "btn-primary mt-3", children: "\u2705 Simpan Satuan Baru" })] })] }) });
}
