import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import AdminLayout from '../../components/AdminLayout';
export default function PpobPage() {
    const bills = [
        { name: 'Listrik', icon: '💡', provider: 'PLN', status: 'Aktif' },
        { name: 'PDAM', icon: '🚰', provider: 'PDAM Kota', status: 'Aktif' },
        { name: 'Pulsa', icon: '📱', provider: 'Telkomsel', status: 'Aktif' },
        { name: 'BPJS', icon: '🏥', provider: 'BPJS Kesehatan', status: 'Segera' },
        { name: 'TV Kabel', icon: '📺', provider: 'Indihome', status: 'Segera' },
        { name: 'Angsuran', icon: '🏦', provider: 'Multifinance', status: 'Segera' },
    ];
    return _jsx(AdminLayout, { children: _jsxs("div", { className: "space-y-4 max-w-4xl mx-auto", children: [_jsx("div", { className: "page-header", children: _jsxs("div", { children: [_jsx("h1", { children: "\uD83D\uDCF1 PPOB \u2014 Pembayaran Tagihan" }), _jsx("p", { className: "text-gray-400 text-sm", children: "Bayar tagihan pelanggan & dapatkan komisi" })] }) }), _jsx("div", { className: "grid grid-cols-3 md:grid-cols-6 gap-3", children: bills.map((b, i) => (_jsxs("div", { className: `card text-center hover:shadow-md cursor-pointer transition-all ${b.status === 'Segera' ? 'opacity-50' : ''}`, children: [_jsx("div", { className: "text-3xl mb-1", children: b.icon }), _jsx("p", { className: "font-semibold text-sm", children: b.name }), _jsx("p", { className: "text-[0.6rem] text-gray-400", children: b.provider }), _jsx("span", { className: `badge ${b.status === 'Aktif' ? 'badge-green' : 'badge-yellow'} text-[0.55rem]`, children: b.status })] }, i))) }), _jsxs("div", { className: "card", children: [_jsx("h3", { className: "font-bold mb-3", children: "\uD83D\uDD0D Cari Tagihan" }), _jsxs("div", { className: "flex gap-2", children: [_jsx("select", { className: "input-field w-48", children: _jsx("option", { children: "Listrik PLN" }) }), _jsx("input", { className: "input-field flex-1", placeholder: "Nomor ID Pelanggan / Meter" }), _jsx("button", { className: "btn-primary", children: "Cek Tagihan" })] })] }), _jsxs("div", { className: "card", children: [_jsx("h3", { className: "font-bold mb-2", children: "\uD83D\uDCB5 Komisi PPOB" }), _jsx("p", { className: "text-sm text-gray-400", children: "Dapatkan komisi dari setiap pembayaran tagihan yang dilakukan melalui toko Anda." }), _jsxs("div", { className: "grid grid-cols-3 gap-4 mt-3", children: [_jsxs("div", { children: [_jsx("p", { className: "text-gray-400 text-xs", children: "Komisi Hari Ini" }), _jsx("p", { className: "text-xl font-bold text-emerald-600", children: "Rp 0" })] }), _jsxs("div", { children: [_jsx("p", { className: "text-gray-400 text-xs", children: "Bulan Ini" }), _jsx("p", { className: "text-xl font-bold", children: "Rp 0" })] }), _jsxs("div", { children: [_jsx("p", { className: "text-gray-400 text-xs", children: "Total Pelanggan" }), _jsx("p", { className: "text-xl font-bold", children: "0" })] })] })] })] }) });
}
