import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import AdminLayout from '../../components/AdminLayout';
export default function StockMutationPage() {
    const mutations = [
        { date: '2026-07-14', type: 'Penjualan', product: 'Indomie Goreng', qty: -5, stock: 45, ref: 'TRX-001' },
        { date: '2026-07-14', type: 'Pembelian', product: 'Indomie Goreng', qty: 50, stock: 50, ref: 'PO-001' },
        { date: '2026-07-13', type: 'Penjualan', product: 'Aqua 600ml', qty: -3, stock: 47, ref: 'TRX-099' },
        { date: '2026-07-13', type: 'Stok Opname', product: 'Sabun Lifebuoy', qty: -2, stock: 18, ref: 'OP-001' },
        { date: '2026-07-12', type: 'Retur', product: 'Rokok Mild', qty: -1, stock: 24, ref: 'RET-001' },
    ];
    return _jsx(AdminLayout, { children: _jsxs("div", { className: "space-y-4 max-w-5xl mx-auto", children: [_jsxs("div", { className: "page-header", children: [_jsxs("div", { children: [_jsx("h1", { children: "\uD83D\uDCCA Mutasi Stok" }), _jsx("p", { className: "text-gray-400 text-sm", children: "Riwayat pergerakan barang masuk & keluar" })] }), _jsxs("div", { className: "flex gap-2", children: [_jsx("input", { className: "input-field w-48", placeholder: "Cari produk..." }), _jsxs("select", { className: "input-field w-36", children: [_jsx("option", { children: "Semua" }), _jsx("option", { children: "Hari Ini" }), _jsx("option", { children: "Minggu Ini" }), _jsx("option", { children: "Bulan Ini" })] })] })] }), _jsx("div", { className: "table-wrap", children: _jsxs("table", { children: [_jsx("thead", { children: _jsxs("tr", { children: [_jsx("th", { children: "Tanggal" }), _jsx("th", { children: "Tipe" }), _jsx("th", { children: "Produk" }), _jsx("th", { children: "Qty" }), _jsx("th", { children: "Sisa Stok" }), _jsx("th", { children: "Ref" })] }) }), _jsx("tbody", { children: mutations.map((m, i) => (_jsxs("tr", { children: [_jsx("td", { className: "text-sm", children: m.date }), _jsx("td", { children: _jsx("span", { className: `badge ${m.type === 'Penjualan' ? 'badge-blue' : m.type === 'Pembelian' ? 'badge-green' : 'badge-yellow'}`, children: m.type }) }), _jsx("td", { className: "font-medium", children: m.product }), _jsx("td", { className: `font-bold ${m.qty > 0 ? 'text-emerald-600' : 'text-red-600'}`, children: m.qty > 0 ? `+${m.qty}` : m.qty }), _jsx("td", { children: m.stock }), _jsx("td", { className: "text-xs text-gray-400", children: m.ref })] }, i))) })] }) }), _jsxs("div", { className: "card", children: [_jsx("h3", { className: "font-bold mb-3", children: "\uD83D\uDCC8 Ringkasan Hari Ini" }), _jsxs("div", { className: "grid grid-cols-3 gap-4", children: [_jsxs("div", { children: [_jsx("p", { className: "text-gray-400 text-xs", children: "Barang Masuk" }), _jsx("p", { className: "text-2xl font-bold text-emerald-600", children: "+50" })] }), _jsxs("div", { children: [_jsx("p", { className: "text-gray-400 text-xs", children: "Barang Keluar" }), _jsx("p", { className: "text-2xl font-bold text-red-600", children: "-8" })] }), _jsxs("div", { children: [_jsx("p", { className: "text-gray-400 text-xs", children: "Produk Terjual" }), _jsx("p", { className: "text-2xl font-bold", children: "2 item" })] })] })] })] }) });
}
